# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1279, 821)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollAreaMap = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaMap.setGeometry(QtCore.QRect(310, 110, 650, 650))
        self.scrollAreaMap.setWidgetResizable(True)
        self.scrollAreaMap.setObjectName("scrollAreaMap")
        self.scrollAreaMapWidgetContents = QtWidgets.QWidget()
        self.scrollAreaMapWidgetContents.setGeometry(QtCore.QRect(0, 0, 648, 648))
        self.scrollAreaMapWidgetContents.setObjectName("scrollAreaMapWidgetContents")
        self.scrollAreaMap.setWidget(self.scrollAreaMapWidgetContents)
        self.labelInput = QtWidgets.QLabel(self.centralwidget)
        self.labelInput.setGeometry(QtCore.QRect(20, 20, 251, 161))
        self.labelInput.setObjectName("labelInput")
        self.labelZoomed = QtWidgets.QLabel(self.centralwidget)
        self.labelZoomed.setGeometry(QtCore.QRect(20, 240, 251, 251))
        self.labelZoomed.setObjectName("labelZoomed")
        self.labelFiltered = QtWidgets.QLabel(self.centralwidget)
        self.labelFiltered.setGeometry(QtCore.QRect(20, 500, 250, 250))
        self.labelFiltered.setObjectName("labelFiltered")
        self.labelMapName = QtWidgets.QLabel(self.centralwidget)
        self.labelMapName.setGeometry(QtCore.QRect(20, 210, 181, 21))
        self.labelMapName.setObjectName("labelMapName")
        self.comboBoxConv = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxConv.setGeometry(QtCore.QRect(400, 60, 541, 23))
        self.comboBoxConv.setObjectName("comboBoxConv")
        self.comboBoxFC = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxFC.setGeometry(QtCore.QRect(980, 60, 251, 23))
        self.comboBoxFC.setObjectName("comboBoxFC")
        self.labelMapNum = QtWidgets.QLabel(self.centralwidget)
        self.labelMapNum.setGeometry(QtCore.QRect(210, 210, 61, 21))
        self.labelMapNum.setText("")
        self.labelMapNum.setObjectName("labelMapNum")
        self.checkBoxColoredGreyScale = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxColoredGreyScale.setGeometry(QtCore.QRect(1100, 20, 141, 21))
        self.checkBoxColoredGreyScale.setChecked(True)
        self.checkBoxColoredGreyScale.setObjectName("checkBoxColoredGreyScale")
        self.labelMapDense = QtWidgets.QLabel(self.centralwidget)
        self.labelMapDense.setGeometry(QtCore.QRect(990, 110, 71, 651))
        self.labelMapDense.setText("")
        self.labelMapDense.setObjectName("labelMapDense")
        self.scrollAreaDense = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaDense.setGeometry(QtCore.QRect(1080, 110, 171, 581))
        self.scrollAreaDense.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaDense.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollAreaDense.setWidgetResizable(True)
        self.scrollAreaDense.setObjectName("scrollAreaDense")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 156, 579))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaDense.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1080, 740, 81, 21))
        self.label.setObjectName("label")
        self.labelDenseName = QtWidgets.QLabel(self.centralwidget)
        self.labelDenseName.setGeometry(QtCore.QRect(1080, 710, 101, 21))
        self.labelDenseName.setText("")
        self.labelDenseName.setObjectName("labelDenseName")
        self.labelDenseNum = QtWidgets.QLabel(self.centralwidget)
        self.labelDenseNum.setGeometry(QtCore.QRect(1190, 710, 51, 21))
        self.labelDenseNum.setText("")
        self.labelDenseNum.setObjectName("labelDenseNum")
        self.labelDenseVal = QtWidgets.QLabel(self.centralwidget)
        self.labelDenseVal.setGeometry(QtCore.QRect(1170, 740, 71, 21))
        self.labelDenseVal.setText("")
        self.labelDenseVal.setObjectName("labelDenseVal")
        self.pushButtonPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlay.setGeometry(QtCore.QRect(320, 60, 51, 31))
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1279, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.checkBoxColoredGreyScale.stateChanged['int'].connect(MainWindow.changeColorMode)
        self.pushButtonPlay.released.connect(MainWindow.PausePlay)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelInput.setText(_translate("MainWindow", "realtime"))
        self.labelZoomed.setText(_translate("MainWindow", "TextLabel"))
        self.labelFiltered.setText(_translate("MainWindow", "Your advertisement here"))
        self.labelMapName.setText(_translate("MainWindow", "Not chosen"))
        self.checkBoxColoredGreyScale.setText(_translate("MainWindow", "Colored / GreyScale"))
        self.label.setText(_translate("MainWindow", "Value"))
        self.pushButtonPlay.setText(_translate("MainWindow", "Pause"))

